AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Alexa Rigatoni Dorati Skill app description
Resources:
  alexarigatonidorati:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole 
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
  pollingMenu:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: crawler.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: 'Polling the menu from the DSU web site'
      MemorySize: 128
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole 
  pollingMenusCurrentWeek:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: cron(0 9 ? * MON *)
      Targets:
        - Id: pollingMenuMartiriCurrentWeek
          Arn: !GetAtt pollingMenu.Arn
          Input: '{"canteen": "martiri", "deltaWeek": 0}'
        - Id: pollingMenuRoselliniCurrentWeek
          Arn: !GetAtt pollingMenu.Arn
          Input: '{"canteen": "rosellini", "deltaWeek": 0}'
        - Id: pollingMenuBettiCurrentWeek
          Arn: !GetAtt pollingMenu.Arn
          Input: '{"canteen": "betti", "deltaWeek": 0}'
  pollingMenusNextWeek:
    Type: 'AWS::Events::Rule'
    Properties:
      ScheduleExpression: cron(0 9 ? * SAT *)
      Targets:
        - Id: pollingMenuMartiriNextWeek
          Arn: !GetAtt pollingMenu.Arn
          Input: '{"canteen": "martiri", "deltaWeek": 1}'
        - Id: pollingMenuRoselliniNextWeek
          Arn: !GetAtt pollingMenu.Arn
          Input: '{"canteen": "rosellini", "deltaWeek": 1}'
        - Id: pollingMenuBettiNextWeek
          Arn: !GetAtt pollingMenu.Arn
          Input: '{"canteen": "betti", "deltaWeek": 1}'
